module.exports = Object.freeze({
    //Source
    "SOURCE_REDIS": "SOURCE_REDIS",
    "SOURCE_DATABASE": "SOURCE_DATABASE",
    //Token
    USER_ACCESS_TOKEN: 'USER_ACCESS_TOKEN',
    USER_ACCESS_TOKEN_PRIVATE_KEY: 'USER_ACCESS_TOKEN_PRIVATE_KEY',
    USER_ACCESS_TOKEN_PUBLIC_KEY: 'USER_ACCESS_TOKEN_PUBLIC_KEY',
    //User
    USER_INFO: 'USER_INFO',
});